name: Generate Report

on:
  schedule:
    - cron: '0 */8 * * *' # 每天 UTC 时间 00:00 运行

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/setup-python@v2
      - run: chrome --version
      - name: install dependencies
        run: pip install selenium webdriver_manager lxml pytz
      - run: python action.py
      - run: |
          git config --global user.email "hexdcode@proton.me"
          git config --global user.name "hexdcode"
          git add -A
          git commit -m "Updated file" -a || echo "No changes to commit"
          git push
          
      
